name: Git current package json version
description: 'Get the current version from package.json'

inputs:
  branch_name:
    description: 'Branch name for the new branch'
    required: false
    default: 'update-dist-${{ github.run_id }}'
    type: string
  main_branch:
    description: 'Main branch to merge into'
    required: false
    default: 'main'
    type: string
  GITHUB_PERSONAL_ACCESS_TOKEN:
    description: 'GitHub Personal Access Token with permissions to manage pull requests'
    required: true
    type: string

outputs:
  tag_name:
    description: 'The name of the tag created'
    value: ${{ steps.tag-version.outputs.tag_name }}

runs:
  using: "composite"
  steps:

  - name: Update package json version
    id: tag-version
    shell: bash
    run: |
      pnpm version ${{ github.event.inputs.version }}
      PACKAGE_VERSION=$(node -p "require('./package.json').version")
      echo "new tag version: $PACKAGE_VERSION"
      echo "tag_name=$PACKAGE_VERSION" >> "$GITHUB_OUTPUT"
