name: Git current package json version
description: 'Get the current version from package.json'

outputs:
  tag_name:
    description: 'The name of the tag created'
    value: ${{ steps.tag-version.outputs.tag_name }}

runs:
  using: "composite"
  steps:

  - name: Update package json version
    id: tag-version
    shell: bash
    run: |
      pnpm version ${{ github.event.inputs.version }}
      PACKAGE_VERSION=$(node -p "require('./package.json').version")
      echo "new tag version: $PACKAGE_VERSION"
      echo "tag_name=$PACKAGE_VERSION" >> "$GITHUB_OUTPUT"
