name: 'Node Output Composite Action'
description: 'Runs a Node.js script and uses its output'
icon: arrow-up-right
color: green
inputs:
  version:
    description: 'Version to set'
    type: string
    required: true
  
  version-type:
    required: true
    description: 'Type of version'
    type: choice
    options:
      - major
      - minor
      - patch
  
outputs:
  new-version:
    description: 'new semantic version'
    value: ${{ steps.run-node.outputs.result }}

runs:
  using: 'node20'
  main: 'dist/index.js'
