name: Build and Push Dist

on:
  push:
    branches:
      - main

jobs:  
  build-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Setup git config
        uses: ./.github/actions/git-user

      - name: Check for changes
        id: git-check
        uses: ./.github/actions/git-diff

      - name: Generate branch name
        id: generate-branch-name
        if: steps.git-check.outputs.hasModifications == 'true'
        run: echo "branch_name=update-dist-${{ github.run_id }}" >> "$GITHUB_OUTPUT"

      - name: Create new branch and merge changes
        id: merge-changes
        if: steps.git-check.outputs.hasModifications == 'true'
        uses: ./.github/actions/new-branch-merge
        with:
          branch_name: ${{ steps.generate-branch-name.outputs.branch_name }}
          commit_command: "git add dist && git commit -m 'chore: update dist folder with latest build changes'"
          main_branch: "main"
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PAT }}

      - name: Wait for dist automerge to complete
        if: steps.git-check.outputs.hasModifications == 'true'
        uses: ./.github/actions/wait-for-automerge
        with:
          branch_name: ${{ steps.generate-branch-name.outputs.branch_name }}