name: Tag release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update major.minor.patch'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
    
permissions:
  contents: write

jobs:
  tag-release:
    name: Tag Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: '22'

      - name: Generate branch name
        id: generate-branch-name
        run: echo "branch_name=update-tag-${{ github.run_id }}" >> "$GITHUB_OUTPUT"

      - name: Setup git config
        uses: ./.github/actions/git-user

      - name: Get current package.json version
        id: package-json-version
        uses: ./.github/actions/get-package-json-version

      - name: Output tag name
        run: |
          echo "Tag created: ${{ steps.package-json-version.outputs.tag_name }}" >> $GITHUB_STEP_SUMMARY
          echo "tag_name=${{ steps.package-json-version.outputs.tag_name }}" >> "$GITHUB_OUTPUT"

      - name: Create Github release
        run: |
          gh release create ${{ steps.package-json-version.outputs.tag_name }} \
            --title "Release ${{ steps.package-json-version.outputs.tag_name }}" \
            --notes "Release notes for version ${{ steps.package-json-version.outputs.tag_name }}" \
            --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
