name: Build and Commit Dist

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to set'
        required: true
    
permissions:
  contents: write

jobs:
  tag-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: '22'

      - name: Setup git config
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@users.noreply.github.com"

      - name: Update package json version
        run: |
          pnpm version ${{ github.event.inputs.version }}
          echo "Version set to ${{ github.event.inputs.version }}"

      - name: Push tags
        run: |
          git push origin main --tags
          echo "Pushed tags to origin"

      

        
          

      
        