name: Run Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: '22'

      - name: Install dependencies
        run: pnpm install

      - name: Check typescript types
        run: pnpm run tsc:check

      - name: Run tests
        run: pnpm run test

  build-and-commit-dist:
    needs: test
    name: Build and Commit Dist
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: '22'

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Setup git config
        uses: ./.github/actions/git-user

      - name: Commit dist folder
        run: |
          git add dist
          git commit -m "chore: update dist [skip ci]"

      - name: Push changes
        run: git push