name: Run Tests and Build Dist
description: This workflow runs tests and builds the project, committing changes to the dist folder if there are modifications.

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: '22'

      - name: Install dependencies
        run: pnpm install

      - name: Check typescript types
        run: pnpm run tsc:check

      - name: Run tests
        run: pnpm run test

  build-and-commit-dist:
    needs: test
    name: Build and Commit Dist
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: '22'

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Check for changes
        id: git-check
        run: |
          if git status | grep -q modified
          then
            echo 'Changes found; hasModifications true' && echo "hasModifications=true" >> "$GITHUB_OUTPUT"
          else
            echo 'No changes found; hasModifications false' && echo "hasModifications=false"  >> "$GITHUB_OUTPUT"
          fi

      - name: Setup git config
        if: steps.git-check.outputs.hasModifications == 'true'
        uses: ./.github/actions/git-user

      - name: Commit dist folder
        if: steps.git-check.outputs.hasModifications == 'true'
        run: |
          git add dist
          git commit -m "chore: update dist [skip ci]"

      - name: Push changes
        if: steps.git-check.outputs.hasModifications == 'true'
        run: |
          git push origin ${{ github.head_ref }}
          echo "Pushed changes to origin"