name: Run Tests and Build Dist
description: This workflow runs tests and builds the project, committing changes to the dist folder if there are modifications.

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: '22'

      - name: Install dependencies
        run: pnpm install

      - name: Check typescript types
        run: pnpm run tsc:check

      - name: Run tests
        run: pnpm run test